name: DevBuild

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install dependencies
      run: dotnet restore ./src/SemanticBlazor.sln
    - name: Build
      run: dotnet build ./src/SemanticBlazor.sln --configuration Release --no-restore